# Generated by Django 3.1 on 2020-11-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hustlers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
